/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VignetteImport } from './routes/vignette'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as Import } from './routes/*'
import { Route as ComponentsRouteImport } from './routes/components_/route'
import { Route as IndexImport } from './routes/index'
import { Route as ComponentsWordCloudImport } from './routes/components_/word-cloud'
import { Route as ComponentsTooltipImport } from './routes/components_/tooltip'
import { Route as ComponentsToggleBarImport } from './routes/components_/toggle-bar'
import { Route as ComponentsTimeSeriesImport } from './routes/components_/time-series'
import { Route as ComponentsTableImport } from './routes/components_/table'
import { Route as ComponentsMetaFrequencyImport } from './routes/components_/meta-frequency'
import { Route as ComponentsMeasureImport } from './routes/components_/measure'
import { Route as ComponentsInputImport } from './routes/components_/input'
import { Route as ComponentsGraphImport } from './routes/components_/graph'
import { Route as ComponentsErrorImport } from './routes/components_/error'
import { Route as ComponentsEllipsisImport } from './routes/components_/ellipsis'
import { Route as ComponentsDiscoursemeCollocateTableImport } from './routes/components_/discourseme-collocate-table'
import { Route as ComponentsDiscoursemeBreakdownImport } from './routes/components_/discourseme-breakdown'
import { Route as ComponentsAssociationMatrixImport } from './routes/components_/association-matrix'
import { Route as AppAdminImport } from './routes/_app/admin'
import { Route as AppSubcorporaRouteImport } from './routes/_app/subcorpora/route'
import { Route as AppQueriesRouteImport } from './routes/_app/queries/route'
import { Route as AppPartitionRouteImport } from './routes/_app/partition/route'
import { Route as AppKeywordAnalysisRouteImport } from './routes/_app/keyword-analysis/route'
import { Route as AppDiscoursemesRouteImport } from './routes/_app/discoursemes/route'
import { Route as AppCorporaRouteImport } from './routes/_app/corpora/route'
import { Route as AppConstellationsRouteImport } from './routes/_app/constellations/route'
import { Route as ComponentsWordCloudFullImport } from './routes/components.word-cloud.full'
import { Route as AppSubcorporaNewImport } from './routes/_app/subcorpora_/new'
import { Route as AppSubcorporaSubcorpusIdImport } from './routes/_app/subcorpora_/$subcorpusId'
import { Route as AppQueriesNewImport } from './routes/_app/queries_/new'
import { Route as AppKeywordAnalysisNewImport } from './routes/_app/keyword-analysis_/new'
import { Route as AppDiscoursemesDiscoursemeIdImport } from './routes/_app/discoursemes_/$discoursemeId'
import { Route as AppCorporaCorpusIdImport } from './routes/_app/corpora_/$corpusId'
import { Route as AppConstellationsNewImport } from './routes/_app/constellations_/new'
import { Route as AppQueriesQueryIdRouteImport } from './routes/_app/queries_/$queryId/route'
import { Route as AppKeywordAnalysisAnalysisIdRouteImport } from './routes/_app/keyword-analysis_/$analysisId/route'
import { Route as AppConstellationsConstellationIdRouteImport } from './routes/_app/constellations_/$constellationId/route'
import { Route as AppQueriesQueryIdSemanticMapImport } from './routes/_app/queries_/$queryId/semantic-map'
import { Route as AppKeywordAnalysisAnalysisIdSemanticMapImport } from './routes/_app/keyword-analysis_/$analysisId/semantic-map'
import { Route as AppDiscoursemesDiscoursemeIdNewDescriptionImport } from './routes/_app/discoursemes_/$discoursemeId_/new-description'
import { Route as AppConstellationsConstellationIdSemanticMapImport } from './routes/_app/constellations_/$constellationId/semantic-map'

// Create Virtual Routes

const LogoutLazyImport = createFileRoute('/logout')()
const AppDiscoursemesNewLazyImport = createFileRoute(
  '/_app/discoursemes_/new',
)()

// Create/Update Routes

const LogoutLazyRoute = LogoutLazyImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout.lazy').then((d) => d.Route))

const VignetteRoute = VignetteImport.update({
  id: '/vignette',
  path: '/vignette',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_app.lazy').then((d) => d.Route))

const Route = Import.update({
  id: '/*',
  path: '/*',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsRouteRoute = ComponentsRouteImport.update({
  id: '/components_',
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsWordCloudRoute = ComponentsWordCloudImport.update({
  id: '/word-cloud',
  path: '/word-cloud',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsTooltipRoute = ComponentsTooltipImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsToggleBarRoute = ComponentsToggleBarImport.update({
  id: '/toggle-bar',
  path: '/toggle-bar',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsTimeSeriesRoute = ComponentsTimeSeriesImport.update({
  id: '/time-series',
  path: '/time-series',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsTableRoute = ComponentsTableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsMetaFrequencyRoute = ComponentsMetaFrequencyImport.update({
  id: '/meta-frequency',
  path: '/meta-frequency',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsMeasureRoute = ComponentsMeasureImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsInputRoute = ComponentsInputImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsGraphRoute = ComponentsGraphImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsErrorRoute = ComponentsErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsEllipsisRoute = ComponentsEllipsisImport.update({
  id: '/ellipsis',
  path: '/ellipsis',
  getParentRoute: () => ComponentsRouteRoute,
} as any)

const ComponentsDiscoursemeCollocateTableRoute =
  ComponentsDiscoursemeCollocateTableImport.update({
    id: '/discourseme-collocate-table',
    path: '/discourseme-collocate-table',
    getParentRoute: () => ComponentsRouteRoute,
  } as any)

const ComponentsDiscoursemeBreakdownRoute =
  ComponentsDiscoursemeBreakdownImport.update({
    id: '/discourseme-breakdown',
    path: '/discourseme-breakdown',
    getParentRoute: () => ComponentsRouteRoute,
  } as any)

const ComponentsAssociationMatrixRoute =
  ComponentsAssociationMatrixImport.update({
    id: '/association-matrix',
    path: '/association-matrix',
    getParentRoute: () => ComponentsRouteRoute,
  } as any)

const AppAdminRoute = AppAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

const AppSubcorporaRouteRoute = AppSubcorporaRouteImport.update({
  id: '/subcorpora',
  path: '/subcorpora',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/subcorpora/route.lazy').then((d) => d.Route),
)

const AppQueriesRouteRoute = AppQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/queries/route.lazy').then((d) => d.Route),
)

const AppPartitionRouteRoute = AppPartitionRouteImport.update({
  id: '/partition',
  path: '/partition',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/partition/route.lazy').then((d) => d.Route),
)

const AppKeywordAnalysisRouteRoute = AppKeywordAnalysisRouteImport.update({
  id: '/keyword-analysis',
  path: '/keyword-analysis',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/keyword-analysis/route.lazy').then((d) => d.Route),
)

const AppDiscoursemesRouteRoute = AppDiscoursemesRouteImport.update({
  id: '/discoursemes',
  path: '/discoursemes',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/discoursemes/route.lazy').then((d) => d.Route),
)

const AppCorporaRouteRoute = AppCorporaRouteImport.update({
  id: '/corpora',
  path: '/corpora',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/corpora/route.lazy').then((d) => d.Route),
)

const AppConstellationsRouteRoute = AppConstellationsRouteImport.update({
  id: '/constellations',
  path: '/constellations',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/constellations/route.lazy').then((d) => d.Route),
)

const AppDiscoursemesNewLazyRoute = AppDiscoursemesNewLazyImport.update({
  id: '/discoursemes_/new',
  path: '/discoursemes/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/discoursemes_/new.lazy').then((d) => d.Route),
)

const ComponentsWordCloudFullRoute = ComponentsWordCloudFullImport.update({
  id: '/components/word-cloud/full',
  path: '/components/word-cloud/full',
  getParentRoute: () => rootRoute,
} as any)

const AppSubcorporaNewRoute = AppSubcorporaNewImport.update({
  id: '/subcorpora_/new',
  path: '/subcorpora/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/subcorpora_/new.lazy').then((d) => d.Route),
)

const AppSubcorporaSubcorpusIdRoute = AppSubcorporaSubcorpusIdImport.update({
  id: '/subcorpora_/$subcorpusId',
  path: '/subcorpora/$subcorpusId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/subcorpora_/$subcorpusId.lazy').then((d) => d.Route),
)

const AppQueriesNewRoute = AppQueriesNewImport.update({
  id: '/queries_/new',
  path: '/queries/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/queries_/new.lazy').then((d) => d.Route),
)

const AppKeywordAnalysisNewRoute = AppKeywordAnalysisNewImport.update({
  id: '/keyword-analysis_/new',
  path: '/keyword-analysis/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/keyword-analysis_/new.lazy').then((d) => d.Route),
)

const AppDiscoursemesDiscoursemeIdRoute =
  AppDiscoursemesDiscoursemeIdImport.update({
    id: '/discoursemes_/$discoursemeId',
    path: '/discoursemes/$discoursemeId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/discoursemes_/$discoursemeId.lazy').then(
      (d) => d.Route,
    ),
  )

const AppCorporaCorpusIdRoute = AppCorporaCorpusIdImport.update({
  id: '/corpora_/$corpusId',
  path: '/corpora/$corpusId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/corpora_/$corpusId.lazy').then((d) => d.Route),
)

const AppConstellationsNewRoute = AppConstellationsNewImport.update({
  id: '/constellations_/new',
  path: '/constellations/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/constellations_/new.lazy').then((d) => d.Route),
)

const AppQueriesQueryIdRouteRoute = AppQueriesQueryIdRouteImport.update({
  id: '/queries_/$queryId',
  path: '/queries/$queryId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/queries_/$queryId/route.lazy').then((d) => d.Route),
)

const AppKeywordAnalysisAnalysisIdRouteRoute =
  AppKeywordAnalysisAnalysisIdRouteImport.update({
    id: '/keyword-analysis_/$analysisId',
    path: '/keyword-analysis/$analysisId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/keyword-analysis_/$analysisId/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AppConstellationsConstellationIdRouteRoute =
  AppConstellationsConstellationIdRouteImport.update({
    id: '/constellations_/$constellationId',
    path: '/constellations/$constellationId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/constellations_/$constellationId/route.lazy').then(
      (d) => d.Route,
    ),
  )

const AppQueriesQueryIdSemanticMapRoute =
  AppQueriesQueryIdSemanticMapImport.update({
    id: '/semantic-map',
    path: '/semantic-map',
    getParentRoute: () => AppQueriesQueryIdRouteRoute,
  } as any)

const AppKeywordAnalysisAnalysisIdSemanticMapRoute =
  AppKeywordAnalysisAnalysisIdSemanticMapImport.update({
    id: '/semantic-map',
    path: '/semantic-map',
    getParentRoute: () => AppKeywordAnalysisAnalysisIdRouteRoute,
  } as any)

const AppDiscoursemesDiscoursemeIdNewDescriptionRoute =
  AppDiscoursemesDiscoursemeIdNewDescriptionImport.update({
    id: '/discoursemes_/$discoursemeId_/new-description',
    path: '/discoursemes/$discoursemeId/new-description',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import(
      './routes/_app/discoursemes_/$discoursemeId_/new-description.lazy'
    ).then((d) => d.Route),
  )

const AppConstellationsConstellationIdSemanticMapRoute =
  AppConstellationsConstellationIdSemanticMapImport.update({
    id: '/semantic-map',
    path: '/semantic-map',
    getParentRoute: () => AppConstellationsConstellationIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/components_': {
      id: '/components_'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRoute
    }
    '/*': {
      id: '/*'
      path: '/*'
      fullPath: '/*'
      preLoaderRoute: typeof Import
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/vignette': {
      id: '/vignette'
      path: '/vignette'
      fullPath: '/vignette'
      preLoaderRoute: typeof VignetteImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/constellations': {
      id: '/_app/constellations'
      path: '/constellations'
      fullPath: '/constellations'
      preLoaderRoute: typeof AppConstellationsRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/corpora': {
      id: '/_app/corpora'
      path: '/corpora'
      fullPath: '/corpora'
      preLoaderRoute: typeof AppCorporaRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/discoursemes': {
      id: '/_app/discoursemes'
      path: '/discoursemes'
      fullPath: '/discoursemes'
      preLoaderRoute: typeof AppDiscoursemesRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/keyword-analysis': {
      id: '/_app/keyword-analysis'
      path: '/keyword-analysis'
      fullPath: '/keyword-analysis'
      preLoaderRoute: typeof AppKeywordAnalysisRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/partition': {
      id: '/_app/partition'
      path: '/partition'
      fullPath: '/partition'
      preLoaderRoute: typeof AppPartitionRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/queries': {
      id: '/_app/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof AppQueriesRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/subcorpora': {
      id: '/_app/subcorpora'
      path: '/subcorpora'
      fullPath: '/subcorpora'
      preLoaderRoute: typeof AppSubcorporaRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminImport
      parentRoute: typeof AppImport
    }
    '/components_/association-matrix': {
      id: '/components_/association-matrix'
      path: '/association-matrix'
      fullPath: '/components/association-matrix'
      preLoaderRoute: typeof ComponentsAssociationMatrixImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/discourseme-breakdown': {
      id: '/components_/discourseme-breakdown'
      path: '/discourseme-breakdown'
      fullPath: '/components/discourseme-breakdown'
      preLoaderRoute: typeof ComponentsDiscoursemeBreakdownImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/discourseme-collocate-table': {
      id: '/components_/discourseme-collocate-table'
      path: '/discourseme-collocate-table'
      fullPath: '/components/discourseme-collocate-table'
      preLoaderRoute: typeof ComponentsDiscoursemeCollocateTableImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/ellipsis': {
      id: '/components_/ellipsis'
      path: '/ellipsis'
      fullPath: '/components/ellipsis'
      preLoaderRoute: typeof ComponentsEllipsisImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/error': {
      id: '/components_/error'
      path: '/error'
      fullPath: '/components/error'
      preLoaderRoute: typeof ComponentsErrorImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/graph': {
      id: '/components_/graph'
      path: '/graph'
      fullPath: '/components/graph'
      preLoaderRoute: typeof ComponentsGraphImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/input': {
      id: '/components_/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/measure': {
      id: '/components_/measure'
      path: '/measure'
      fullPath: '/components/measure'
      preLoaderRoute: typeof ComponentsMeasureImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/meta-frequency': {
      id: '/components_/meta-frequency'
      path: '/meta-frequency'
      fullPath: '/components/meta-frequency'
      preLoaderRoute: typeof ComponentsMetaFrequencyImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/table': {
      id: '/components_/table'
      path: '/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/time-series': {
      id: '/components_/time-series'
      path: '/time-series'
      fullPath: '/components/time-series'
      preLoaderRoute: typeof ComponentsTimeSeriesImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/toggle-bar': {
      id: '/components_/toggle-bar'
      path: '/toggle-bar'
      fullPath: '/components/toggle-bar'
      preLoaderRoute: typeof ComponentsToggleBarImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/tooltip': {
      id: '/components_/tooltip'
      path: '/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/components_/word-cloud': {
      id: '/components_/word-cloud'
      path: '/word-cloud'
      fullPath: '/components/word-cloud'
      preLoaderRoute: typeof ComponentsWordCloudImport
      parentRoute: typeof ComponentsRouteImport
    }
    '/_app/constellations_/$constellationId': {
      id: '/_app/constellations_/$constellationId'
      path: '/constellations/$constellationId'
      fullPath: '/constellations/$constellationId'
      preLoaderRoute: typeof AppConstellationsConstellationIdRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/keyword-analysis_/$analysisId': {
      id: '/_app/keyword-analysis_/$analysisId'
      path: '/keyword-analysis/$analysisId'
      fullPath: '/keyword-analysis/$analysisId'
      preLoaderRoute: typeof AppKeywordAnalysisAnalysisIdRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/queries_/$queryId': {
      id: '/_app/queries_/$queryId'
      path: '/queries/$queryId'
      fullPath: '/queries/$queryId'
      preLoaderRoute: typeof AppQueriesQueryIdRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/constellations_/new': {
      id: '/_app/constellations_/new'
      path: '/constellations/new'
      fullPath: '/constellations/new'
      preLoaderRoute: typeof AppConstellationsNewImport
      parentRoute: typeof AppImport
    }
    '/_app/corpora_/$corpusId': {
      id: '/_app/corpora_/$corpusId'
      path: '/corpora/$corpusId'
      fullPath: '/corpora/$corpusId'
      preLoaderRoute: typeof AppCorporaCorpusIdImport
      parentRoute: typeof AppImport
    }
    '/_app/discoursemes_/$discoursemeId': {
      id: '/_app/discoursemes_/$discoursemeId'
      path: '/discoursemes/$discoursemeId'
      fullPath: '/discoursemes/$discoursemeId'
      preLoaderRoute: typeof AppDiscoursemesDiscoursemeIdImport
      parentRoute: typeof AppImport
    }
    '/_app/keyword-analysis_/new': {
      id: '/_app/keyword-analysis_/new'
      path: '/keyword-analysis/new'
      fullPath: '/keyword-analysis/new'
      preLoaderRoute: typeof AppKeywordAnalysisNewImport
      parentRoute: typeof AppImport
    }
    '/_app/queries_/new': {
      id: '/_app/queries_/new'
      path: '/queries/new'
      fullPath: '/queries/new'
      preLoaderRoute: typeof AppQueriesNewImport
      parentRoute: typeof AppImport
    }
    '/_app/subcorpora_/$subcorpusId': {
      id: '/_app/subcorpora_/$subcorpusId'
      path: '/subcorpora/$subcorpusId'
      fullPath: '/subcorpora/$subcorpusId'
      preLoaderRoute: typeof AppSubcorporaSubcorpusIdImport
      parentRoute: typeof AppImport
    }
    '/_app/subcorpora_/new': {
      id: '/_app/subcorpora_/new'
      path: '/subcorpora/new'
      fullPath: '/subcorpora/new'
      preLoaderRoute: typeof AppSubcorporaNewImport
      parentRoute: typeof AppImport
    }
    '/components/word-cloud/full': {
      id: '/components/word-cloud/full'
      path: '/components/word-cloud/full'
      fullPath: '/components/word-cloud/full'
      preLoaderRoute: typeof ComponentsWordCloudFullImport
      parentRoute: typeof rootRoute
    }
    '/_app/discoursemes_/new': {
      id: '/_app/discoursemes_/new'
      path: '/discoursemes/new'
      fullPath: '/discoursemes/new'
      preLoaderRoute: typeof AppDiscoursemesNewLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/constellations_/$constellationId/semantic-map': {
      id: '/_app/constellations_/$constellationId/semantic-map'
      path: '/semantic-map'
      fullPath: '/constellations/$constellationId/semantic-map'
      preLoaderRoute: typeof AppConstellationsConstellationIdSemanticMapImport
      parentRoute: typeof AppConstellationsConstellationIdRouteImport
    }
    '/_app/discoursemes_/$discoursemeId_/new-description': {
      id: '/_app/discoursemes_/$discoursemeId_/new-description'
      path: '/discoursemes/$discoursemeId/new-description'
      fullPath: '/discoursemes/$discoursemeId/new-description'
      preLoaderRoute: typeof AppDiscoursemesDiscoursemeIdNewDescriptionImport
      parentRoute: typeof AppImport
    }
    '/_app/keyword-analysis_/$analysisId/semantic-map': {
      id: '/_app/keyword-analysis_/$analysisId/semantic-map'
      path: '/semantic-map'
      fullPath: '/keyword-analysis/$analysisId/semantic-map'
      preLoaderRoute: typeof AppKeywordAnalysisAnalysisIdSemanticMapImport
      parentRoute: typeof AppKeywordAnalysisAnalysisIdRouteImport
    }
    '/_app/queries_/$queryId/semantic-map': {
      id: '/_app/queries_/$queryId/semantic-map'
      path: '/semantic-map'
      fullPath: '/queries/$queryId/semantic-map'
      preLoaderRoute: typeof AppQueriesQueryIdSemanticMapImport
      parentRoute: typeof AppQueriesQueryIdRouteImport
    }
  }
}

// Create and export the route tree

interface ComponentsRouteRouteChildren {
  ComponentsAssociationMatrixRoute: typeof ComponentsAssociationMatrixRoute
  ComponentsDiscoursemeBreakdownRoute: typeof ComponentsDiscoursemeBreakdownRoute
  ComponentsDiscoursemeCollocateTableRoute: typeof ComponentsDiscoursemeCollocateTableRoute
  ComponentsEllipsisRoute: typeof ComponentsEllipsisRoute
  ComponentsErrorRoute: typeof ComponentsErrorRoute
  ComponentsGraphRoute: typeof ComponentsGraphRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsMeasureRoute: typeof ComponentsMeasureRoute
  ComponentsMetaFrequencyRoute: typeof ComponentsMetaFrequencyRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTimeSeriesRoute: typeof ComponentsTimeSeriesRoute
  ComponentsToggleBarRoute: typeof ComponentsToggleBarRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsWordCloudRoute: typeof ComponentsWordCloudRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsAssociationMatrixRoute: ComponentsAssociationMatrixRoute,
  ComponentsDiscoursemeBreakdownRoute: ComponentsDiscoursemeBreakdownRoute,
  ComponentsDiscoursemeCollocateTableRoute:
    ComponentsDiscoursemeCollocateTableRoute,
  ComponentsEllipsisRoute: ComponentsEllipsisRoute,
  ComponentsErrorRoute: ComponentsErrorRoute,
  ComponentsGraphRoute: ComponentsGraphRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsMeasureRoute: ComponentsMeasureRoute,
  ComponentsMetaFrequencyRoute: ComponentsMetaFrequencyRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTimeSeriesRoute: ComponentsTimeSeriesRoute,
  ComponentsToggleBarRoute: ComponentsToggleBarRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsWordCloudRoute: ComponentsWordCloudRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

interface AppConstellationsConstellationIdRouteRouteChildren {
  AppConstellationsConstellationIdSemanticMapRoute: typeof AppConstellationsConstellationIdSemanticMapRoute
}

const AppConstellationsConstellationIdRouteRouteChildren: AppConstellationsConstellationIdRouteRouteChildren =
  {
    AppConstellationsConstellationIdSemanticMapRoute:
      AppConstellationsConstellationIdSemanticMapRoute,
  }

const AppConstellationsConstellationIdRouteRouteWithChildren =
  AppConstellationsConstellationIdRouteRoute._addFileChildren(
    AppConstellationsConstellationIdRouteRouteChildren,
  )

interface AppKeywordAnalysisAnalysisIdRouteRouteChildren {
  AppKeywordAnalysisAnalysisIdSemanticMapRoute: typeof AppKeywordAnalysisAnalysisIdSemanticMapRoute
}

const AppKeywordAnalysisAnalysisIdRouteRouteChildren: AppKeywordAnalysisAnalysisIdRouteRouteChildren =
  {
    AppKeywordAnalysisAnalysisIdSemanticMapRoute:
      AppKeywordAnalysisAnalysisIdSemanticMapRoute,
  }

const AppKeywordAnalysisAnalysisIdRouteRouteWithChildren =
  AppKeywordAnalysisAnalysisIdRouteRoute._addFileChildren(
    AppKeywordAnalysisAnalysisIdRouteRouteChildren,
  )

interface AppQueriesQueryIdRouteRouteChildren {
  AppQueriesQueryIdSemanticMapRoute: typeof AppQueriesQueryIdSemanticMapRoute
}

const AppQueriesQueryIdRouteRouteChildren: AppQueriesQueryIdRouteRouteChildren =
  {
    AppQueriesQueryIdSemanticMapRoute: AppQueriesQueryIdSemanticMapRoute,
  }

const AppQueriesQueryIdRouteRouteWithChildren =
  AppQueriesQueryIdRouteRoute._addFileChildren(
    AppQueriesQueryIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppConstellationsRouteRoute: typeof AppConstellationsRouteRoute
  AppCorporaRouteRoute: typeof AppCorporaRouteRoute
  AppDiscoursemesRouteRoute: typeof AppDiscoursemesRouteRoute
  AppKeywordAnalysisRouteRoute: typeof AppKeywordAnalysisRouteRoute
  AppPartitionRouteRoute: typeof AppPartitionRouteRoute
  AppQueriesRouteRoute: typeof AppQueriesRouteRoute
  AppSubcorporaRouteRoute: typeof AppSubcorporaRouteRoute
  AppAdminRoute: typeof AppAdminRoute
  AppConstellationsConstellationIdRouteRoute: typeof AppConstellationsConstellationIdRouteRouteWithChildren
  AppKeywordAnalysisAnalysisIdRouteRoute: typeof AppKeywordAnalysisAnalysisIdRouteRouteWithChildren
  AppQueriesQueryIdRouteRoute: typeof AppQueriesQueryIdRouteRouteWithChildren
  AppConstellationsNewRoute: typeof AppConstellationsNewRoute
  AppCorporaCorpusIdRoute: typeof AppCorporaCorpusIdRoute
  AppDiscoursemesDiscoursemeIdRoute: typeof AppDiscoursemesDiscoursemeIdRoute
  AppKeywordAnalysisNewRoute: typeof AppKeywordAnalysisNewRoute
  AppQueriesNewRoute: typeof AppQueriesNewRoute
  AppSubcorporaSubcorpusIdRoute: typeof AppSubcorporaSubcorpusIdRoute
  AppSubcorporaNewRoute: typeof AppSubcorporaNewRoute
  AppDiscoursemesNewLazyRoute: typeof AppDiscoursemesNewLazyRoute
  AppDiscoursemesDiscoursemeIdNewDescriptionRoute: typeof AppDiscoursemesDiscoursemeIdNewDescriptionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConstellationsRouteRoute: AppConstellationsRouteRoute,
  AppCorporaRouteRoute: AppCorporaRouteRoute,
  AppDiscoursemesRouteRoute: AppDiscoursemesRouteRoute,
  AppKeywordAnalysisRouteRoute: AppKeywordAnalysisRouteRoute,
  AppPartitionRouteRoute: AppPartitionRouteRoute,
  AppQueriesRouteRoute: AppQueriesRouteRoute,
  AppSubcorporaRouteRoute: AppSubcorporaRouteRoute,
  AppAdminRoute: AppAdminRoute,
  AppConstellationsConstellationIdRouteRoute:
    AppConstellationsConstellationIdRouteRouteWithChildren,
  AppKeywordAnalysisAnalysisIdRouteRoute:
    AppKeywordAnalysisAnalysisIdRouteRouteWithChildren,
  AppQueriesQueryIdRouteRoute: AppQueriesQueryIdRouteRouteWithChildren,
  AppConstellationsNewRoute: AppConstellationsNewRoute,
  AppCorporaCorpusIdRoute: AppCorporaCorpusIdRoute,
  AppDiscoursemesDiscoursemeIdRoute: AppDiscoursemesDiscoursemeIdRoute,
  AppKeywordAnalysisNewRoute: AppKeywordAnalysisNewRoute,
  AppQueriesNewRoute: AppQueriesNewRoute,
  AppSubcorporaSubcorpusIdRoute: AppSubcorporaSubcorpusIdRoute,
  AppSubcorporaNewRoute: AppSubcorporaNewRoute,
  AppDiscoursemesNewLazyRoute: AppDiscoursemesNewLazyRoute,
  AppDiscoursemesDiscoursemeIdNewDescriptionRoute:
    AppDiscoursemesDiscoursemeIdNewDescriptionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/*': typeof Route
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/vignette': typeof VignetteRoute
  '/logout': typeof LogoutLazyRoute
  '/constellations': typeof AppConstellationsRouteRoute
  '/corpora': typeof AppCorporaRouteRoute
  '/discoursemes': typeof AppDiscoursemesRouteRoute
  '/keyword-analysis': typeof AppKeywordAnalysisRouteRoute
  '/partition': typeof AppPartitionRouteRoute
  '/queries': typeof AppQueriesRouteRoute
  '/subcorpora': typeof AppSubcorporaRouteRoute
  '/admin': typeof AppAdminRoute
  '/components/association-matrix': typeof ComponentsAssociationMatrixRoute
  '/components/discourseme-breakdown': typeof ComponentsDiscoursemeBreakdownRoute
  '/components/discourseme-collocate-table': typeof ComponentsDiscoursemeCollocateTableRoute
  '/components/ellipsis': typeof ComponentsEllipsisRoute
  '/components/error': typeof ComponentsErrorRoute
  '/components/graph': typeof ComponentsGraphRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/measure': typeof ComponentsMeasureRoute
  '/components/meta-frequency': typeof ComponentsMetaFrequencyRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/time-series': typeof ComponentsTimeSeriesRoute
  '/components/toggle-bar': typeof ComponentsToggleBarRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/word-cloud': typeof ComponentsWordCloudRoute
  '/constellations/$constellationId': typeof AppConstellationsConstellationIdRouteRouteWithChildren
  '/keyword-analysis/$analysisId': typeof AppKeywordAnalysisAnalysisIdRouteRouteWithChildren
  '/queries/$queryId': typeof AppQueriesQueryIdRouteRouteWithChildren
  '/constellations/new': typeof AppConstellationsNewRoute
  '/corpora/$corpusId': typeof AppCorporaCorpusIdRoute
  '/discoursemes/$discoursemeId': typeof AppDiscoursemesDiscoursemeIdRoute
  '/keyword-analysis/new': typeof AppKeywordAnalysisNewRoute
  '/queries/new': typeof AppQueriesNewRoute
  '/subcorpora/$subcorpusId': typeof AppSubcorporaSubcorpusIdRoute
  '/subcorpora/new': typeof AppSubcorporaNewRoute
  '/components/word-cloud/full': typeof ComponentsWordCloudFullRoute
  '/discoursemes/new': typeof AppDiscoursemesNewLazyRoute
  '/constellations/$constellationId/semantic-map': typeof AppConstellationsConstellationIdSemanticMapRoute
  '/discoursemes/$discoursemeId/new-description': typeof AppDiscoursemesDiscoursemeIdNewDescriptionRoute
  '/keyword-analysis/$analysisId/semantic-map': typeof AppKeywordAnalysisAnalysisIdSemanticMapRoute
  '/queries/$queryId/semantic-map': typeof AppQueriesQueryIdSemanticMapRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/*': typeof Route
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/vignette': typeof VignetteRoute
  '/logout': typeof LogoutLazyRoute
  '/constellations': typeof AppConstellationsRouteRoute
  '/corpora': typeof AppCorporaRouteRoute
  '/discoursemes': typeof AppDiscoursemesRouteRoute
  '/keyword-analysis': typeof AppKeywordAnalysisRouteRoute
  '/partition': typeof AppPartitionRouteRoute
  '/queries': typeof AppQueriesRouteRoute
  '/subcorpora': typeof AppSubcorporaRouteRoute
  '/admin': typeof AppAdminRoute
  '/components/association-matrix': typeof ComponentsAssociationMatrixRoute
  '/components/discourseme-breakdown': typeof ComponentsDiscoursemeBreakdownRoute
  '/components/discourseme-collocate-table': typeof ComponentsDiscoursemeCollocateTableRoute
  '/components/ellipsis': typeof ComponentsEllipsisRoute
  '/components/error': typeof ComponentsErrorRoute
  '/components/graph': typeof ComponentsGraphRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/measure': typeof ComponentsMeasureRoute
  '/components/meta-frequency': typeof ComponentsMetaFrequencyRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/time-series': typeof ComponentsTimeSeriesRoute
  '/components/toggle-bar': typeof ComponentsToggleBarRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/word-cloud': typeof ComponentsWordCloudRoute
  '/constellations/$constellationId': typeof AppConstellationsConstellationIdRouteRouteWithChildren
  '/keyword-analysis/$analysisId': typeof AppKeywordAnalysisAnalysisIdRouteRouteWithChildren
  '/queries/$queryId': typeof AppQueriesQueryIdRouteRouteWithChildren
  '/constellations/new': typeof AppConstellationsNewRoute
  '/corpora/$corpusId': typeof AppCorporaCorpusIdRoute
  '/discoursemes/$discoursemeId': typeof AppDiscoursemesDiscoursemeIdRoute
  '/keyword-analysis/new': typeof AppKeywordAnalysisNewRoute
  '/queries/new': typeof AppQueriesNewRoute
  '/subcorpora/$subcorpusId': typeof AppSubcorporaSubcorpusIdRoute
  '/subcorpora/new': typeof AppSubcorporaNewRoute
  '/components/word-cloud/full': typeof ComponentsWordCloudFullRoute
  '/discoursemes/new': typeof AppDiscoursemesNewLazyRoute
  '/constellations/$constellationId/semantic-map': typeof AppConstellationsConstellationIdSemanticMapRoute
  '/discoursemes/$discoursemeId/new-description': typeof AppDiscoursemesDiscoursemeIdNewDescriptionRoute
  '/keyword-analysis/$analysisId/semantic-map': typeof AppKeywordAnalysisAnalysisIdSemanticMapRoute
  '/queries/$queryId/semantic-map': typeof AppQueriesQueryIdSemanticMapRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/components_': typeof ComponentsRouteRouteWithChildren
  '/*': typeof Route
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/vignette': typeof VignetteRoute
  '/logout': typeof LogoutLazyRoute
  '/_app/constellations': typeof AppConstellationsRouteRoute
  '/_app/corpora': typeof AppCorporaRouteRoute
  '/_app/discoursemes': typeof AppDiscoursemesRouteRoute
  '/_app/keyword-analysis': typeof AppKeywordAnalysisRouteRoute
  '/_app/partition': typeof AppPartitionRouteRoute
  '/_app/queries': typeof AppQueriesRouteRoute
  '/_app/subcorpora': typeof AppSubcorporaRouteRoute
  '/_app/admin': typeof AppAdminRoute
  '/components_/association-matrix': typeof ComponentsAssociationMatrixRoute
  '/components_/discourseme-breakdown': typeof ComponentsDiscoursemeBreakdownRoute
  '/components_/discourseme-collocate-table': typeof ComponentsDiscoursemeCollocateTableRoute
  '/components_/ellipsis': typeof ComponentsEllipsisRoute
  '/components_/error': typeof ComponentsErrorRoute
  '/components_/graph': typeof ComponentsGraphRoute
  '/components_/input': typeof ComponentsInputRoute
  '/components_/measure': typeof ComponentsMeasureRoute
  '/components_/meta-frequency': typeof ComponentsMetaFrequencyRoute
  '/components_/table': typeof ComponentsTableRoute
  '/components_/time-series': typeof ComponentsTimeSeriesRoute
  '/components_/toggle-bar': typeof ComponentsToggleBarRoute
  '/components_/tooltip': typeof ComponentsTooltipRoute
  '/components_/word-cloud': typeof ComponentsWordCloudRoute
  '/_app/constellations_/$constellationId': typeof AppConstellationsConstellationIdRouteRouteWithChildren
  '/_app/keyword-analysis_/$analysisId': typeof AppKeywordAnalysisAnalysisIdRouteRouteWithChildren
  '/_app/queries_/$queryId': typeof AppQueriesQueryIdRouteRouteWithChildren
  '/_app/constellations_/new': typeof AppConstellationsNewRoute
  '/_app/corpora_/$corpusId': typeof AppCorporaCorpusIdRoute
  '/_app/discoursemes_/$discoursemeId': typeof AppDiscoursemesDiscoursemeIdRoute
  '/_app/keyword-analysis_/new': typeof AppKeywordAnalysisNewRoute
  '/_app/queries_/new': typeof AppQueriesNewRoute
  '/_app/subcorpora_/$subcorpusId': typeof AppSubcorporaSubcorpusIdRoute
  '/_app/subcorpora_/new': typeof AppSubcorporaNewRoute
  '/components/word-cloud/full': typeof ComponentsWordCloudFullRoute
  '/_app/discoursemes_/new': typeof AppDiscoursemesNewLazyRoute
  '/_app/constellations_/$constellationId/semantic-map': typeof AppConstellationsConstellationIdSemanticMapRoute
  '/_app/discoursemes_/$discoursemeId_/new-description': typeof AppDiscoursemesDiscoursemeIdNewDescriptionRoute
  '/_app/keyword-analysis_/$analysisId/semantic-map': typeof AppKeywordAnalysisAnalysisIdSemanticMapRoute
  '/_app/queries_/$queryId/semantic-map': typeof AppQueriesQueryIdSemanticMapRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/*'
    | ''
    | '/login'
    | '/vignette'
    | '/logout'
    | '/constellations'
    | '/corpora'
    | '/discoursemes'
    | '/keyword-analysis'
    | '/partition'
    | '/queries'
    | '/subcorpora'
    | '/admin'
    | '/components/association-matrix'
    | '/components/discourseme-breakdown'
    | '/components/discourseme-collocate-table'
    | '/components/ellipsis'
    | '/components/error'
    | '/components/graph'
    | '/components/input'
    | '/components/measure'
    | '/components/meta-frequency'
    | '/components/table'
    | '/components/time-series'
    | '/components/toggle-bar'
    | '/components/tooltip'
    | '/components/word-cloud'
    | '/constellations/$constellationId'
    | '/keyword-analysis/$analysisId'
    | '/queries/$queryId'
    | '/constellations/new'
    | '/corpora/$corpusId'
    | '/discoursemes/$discoursemeId'
    | '/keyword-analysis/new'
    | '/queries/new'
    | '/subcorpora/$subcorpusId'
    | '/subcorpora/new'
    | '/components/word-cloud/full'
    | '/discoursemes/new'
    | '/constellations/$constellationId/semantic-map'
    | '/discoursemes/$discoursemeId/new-description'
    | '/keyword-analysis/$analysisId/semantic-map'
    | '/queries/$queryId/semantic-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/*'
    | ''
    | '/login'
    | '/vignette'
    | '/logout'
    | '/constellations'
    | '/corpora'
    | '/discoursemes'
    | '/keyword-analysis'
    | '/partition'
    | '/queries'
    | '/subcorpora'
    | '/admin'
    | '/components/association-matrix'
    | '/components/discourseme-breakdown'
    | '/components/discourseme-collocate-table'
    | '/components/ellipsis'
    | '/components/error'
    | '/components/graph'
    | '/components/input'
    | '/components/measure'
    | '/components/meta-frequency'
    | '/components/table'
    | '/components/time-series'
    | '/components/toggle-bar'
    | '/components/tooltip'
    | '/components/word-cloud'
    | '/constellations/$constellationId'
    | '/keyword-analysis/$analysisId'
    | '/queries/$queryId'
    | '/constellations/new'
    | '/corpora/$corpusId'
    | '/discoursemes/$discoursemeId'
    | '/keyword-analysis/new'
    | '/queries/new'
    | '/subcorpora/$subcorpusId'
    | '/subcorpora/new'
    | '/components/word-cloud/full'
    | '/discoursemes/new'
    | '/constellations/$constellationId/semantic-map'
    | '/discoursemes/$discoursemeId/new-description'
    | '/keyword-analysis/$analysisId/semantic-map'
    | '/queries/$queryId/semantic-map'
  id:
    | '__root__'
    | '/'
    | '/components_'
    | '/*'
    | '/_app'
    | '/login'
    | '/vignette'
    | '/logout'
    | '/_app/constellations'
    | '/_app/corpora'
    | '/_app/discoursemes'
    | '/_app/keyword-analysis'
    | '/_app/partition'
    | '/_app/queries'
    | '/_app/subcorpora'
    | '/_app/admin'
    | '/components_/association-matrix'
    | '/components_/discourseme-breakdown'
    | '/components_/discourseme-collocate-table'
    | '/components_/ellipsis'
    | '/components_/error'
    | '/components_/graph'
    | '/components_/input'
    | '/components_/measure'
    | '/components_/meta-frequency'
    | '/components_/table'
    | '/components_/time-series'
    | '/components_/toggle-bar'
    | '/components_/tooltip'
    | '/components_/word-cloud'
    | '/_app/constellations_/$constellationId'
    | '/_app/keyword-analysis_/$analysisId'
    | '/_app/queries_/$queryId'
    | '/_app/constellations_/new'
    | '/_app/corpora_/$corpusId'
    | '/_app/discoursemes_/$discoursemeId'
    | '/_app/keyword-analysis_/new'
    | '/_app/queries_/new'
    | '/_app/subcorpora_/$subcorpusId'
    | '/_app/subcorpora_/new'
    | '/components/word-cloud/full'
    | '/_app/discoursemes_/new'
    | '/_app/constellations_/$constellationId/semantic-map'
    | '/_app/discoursemes_/$discoursemeId_/new-description'
    | '/_app/keyword-analysis_/$analysisId/semantic-map'
    | '/_app/queries_/$queryId/semantic-map'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
  Route: typeof Route
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  VignetteRoute: typeof VignetteRoute
  LogoutLazyRoute: typeof LogoutLazyRoute
  ComponentsWordCloudFullRoute: typeof ComponentsWordCloudFullRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
  Route: Route,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  VignetteRoute: VignetteRoute,
  LogoutLazyRoute: LogoutLazyRoute,
  ComponentsWordCloudFullRoute: ComponentsWordCloudFullRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/components_",
        "/*",
        "/_app",
        "/login",
        "/vignette",
        "/logout",
        "/components/word-cloud/full"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/components_": {
      "filePath": "components_/route.tsx",
      "children": [
        "/components_/association-matrix",
        "/components_/discourseme-breakdown",
        "/components_/discourseme-collocate-table",
        "/components_/ellipsis",
        "/components_/error",
        "/components_/graph",
        "/components_/input",
        "/components_/measure",
        "/components_/meta-frequency",
        "/components_/table",
        "/components_/time-series",
        "/components_/toggle-bar",
        "/components_/tooltip",
        "/components_/word-cloud"
      ]
    },
    "/*": {
      "filePath": "*.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/constellations",
        "/_app/corpora",
        "/_app/discoursemes",
        "/_app/keyword-analysis",
        "/_app/partition",
        "/_app/queries",
        "/_app/subcorpora",
        "/_app/admin",
        "/_app/constellations_/$constellationId",
        "/_app/keyword-analysis_/$analysisId",
        "/_app/queries_/$queryId",
        "/_app/constellations_/new",
        "/_app/corpora_/$corpusId",
        "/_app/discoursemes_/$discoursemeId",
        "/_app/keyword-analysis_/new",
        "/_app/queries_/new",
        "/_app/subcorpora_/$subcorpusId",
        "/_app/subcorpora_/new",
        "/_app/discoursemes_/new",
        "/_app/discoursemes_/$discoursemeId_/new-description"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/vignette": {
      "filePath": "vignette.tsx"
    },
    "/logout": {
      "filePath": "logout.lazy.tsx"
    },
    "/_app/constellations": {
      "filePath": "_app/constellations/route.tsx",
      "parent": "/_app"
    },
    "/_app/corpora": {
      "filePath": "_app/corpora/route.tsx",
      "parent": "/_app"
    },
    "/_app/discoursemes": {
      "filePath": "_app/discoursemes/route.tsx",
      "parent": "/_app"
    },
    "/_app/keyword-analysis": {
      "filePath": "_app/keyword-analysis/route.tsx",
      "parent": "/_app"
    },
    "/_app/partition": {
      "filePath": "_app/partition/route.tsx",
      "parent": "/_app"
    },
    "/_app/queries": {
      "filePath": "_app/queries/route.tsx",
      "parent": "/_app"
    },
    "/_app/subcorpora": {
      "filePath": "_app/subcorpora/route.tsx",
      "parent": "/_app"
    },
    "/_app/admin": {
      "filePath": "_app/admin.tsx",
      "parent": "/_app"
    },
    "/components_/association-matrix": {
      "filePath": "components_/association-matrix.tsx",
      "parent": "/components_"
    },
    "/components_/discourseme-breakdown": {
      "filePath": "components_/discourseme-breakdown.tsx",
      "parent": "/components_"
    },
    "/components_/discourseme-collocate-table": {
      "filePath": "components_/discourseme-collocate-table.tsx",
      "parent": "/components_"
    },
    "/components_/ellipsis": {
      "filePath": "components_/ellipsis.tsx",
      "parent": "/components_"
    },
    "/components_/error": {
      "filePath": "components_/error.tsx",
      "parent": "/components_"
    },
    "/components_/graph": {
      "filePath": "components_/graph.tsx",
      "parent": "/components_"
    },
    "/components_/input": {
      "filePath": "components_/input.tsx",
      "parent": "/components_"
    },
    "/components_/measure": {
      "filePath": "components_/measure.tsx",
      "parent": "/components_"
    },
    "/components_/meta-frequency": {
      "filePath": "components_/meta-frequency.tsx",
      "parent": "/components_"
    },
    "/components_/table": {
      "filePath": "components_/table.tsx",
      "parent": "/components_"
    },
    "/components_/time-series": {
      "filePath": "components_/time-series.tsx",
      "parent": "/components_"
    },
    "/components_/toggle-bar": {
      "filePath": "components_/toggle-bar.tsx",
      "parent": "/components_"
    },
    "/components_/tooltip": {
      "filePath": "components_/tooltip.tsx",
      "parent": "/components_"
    },
    "/components_/word-cloud": {
      "filePath": "components_/word-cloud.tsx",
      "parent": "/components_"
    },
    "/_app/constellations_/$constellationId": {
      "filePath": "_app/constellations_/$constellationId/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/constellations_/$constellationId/semantic-map"
      ]
    },
    "/_app/keyword-analysis_/$analysisId": {
      "filePath": "_app/keyword-analysis_/$analysisId/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/keyword-analysis_/$analysisId/semantic-map"
      ]
    },
    "/_app/queries_/$queryId": {
      "filePath": "_app/queries_/$queryId/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/queries_/$queryId/semantic-map"
      ]
    },
    "/_app/constellations_/new": {
      "filePath": "_app/constellations_/new.tsx",
      "parent": "/_app"
    },
    "/_app/corpora_/$corpusId": {
      "filePath": "_app/corpora_/$corpusId.tsx",
      "parent": "/_app"
    },
    "/_app/discoursemes_/$discoursemeId": {
      "filePath": "_app/discoursemes_/$discoursemeId.tsx",
      "parent": "/_app"
    },
    "/_app/keyword-analysis_/new": {
      "filePath": "_app/keyword-analysis_/new.tsx",
      "parent": "/_app"
    },
    "/_app/queries_/new": {
      "filePath": "_app/queries_/new.tsx",
      "parent": "/_app"
    },
    "/_app/subcorpora_/$subcorpusId": {
      "filePath": "_app/subcorpora_/$subcorpusId.tsx",
      "parent": "/_app"
    },
    "/_app/subcorpora_/new": {
      "filePath": "_app/subcorpora_/new.tsx",
      "parent": "/_app"
    },
    "/components/word-cloud/full": {
      "filePath": "components.word-cloud.full.tsx"
    },
    "/_app/discoursemes_/new": {
      "filePath": "_app/discoursemes_/new.lazy.tsx",
      "parent": "/_app"
    },
    "/_app/constellations_/$constellationId/semantic-map": {
      "filePath": "_app/constellations_/$constellationId/semantic-map.tsx",
      "parent": "/_app/constellations_/$constellationId"
    },
    "/_app/discoursemes_/$discoursemeId_/new-description": {
      "filePath": "_app/discoursemes_/$discoursemeId_/new-description.tsx",
      "parent": "/_app"
    },
    "/_app/keyword-analysis_/$analysisId/semantic-map": {
      "filePath": "_app/keyword-analysis_/$analysisId/semantic-map.tsx",
      "parent": "/_app/keyword-analysis_/$analysisId"
    },
    "/_app/queries_/$queryId/semantic-map": {
      "filePath": "_app/queries_/$queryId/semantic-map.tsx",
      "parent": "/_app/queries_/$queryId"
    }
  }
}
ROUTE_MANIFEST_END */
